import type { Product, Order } from "./types";

// Category placeholder colors (warm earth tones)
const COLORS = {
  grain: "#D4A574",
  oil: "#C4956A",
  spice: "#B8860B",
  canned: "#8B7355",
  beverage: "#6B8E6B",
  household: "#9B8EC4",
} as const;

export const products: Product[] = [
  // ── Grains & Rice (6): 5 In Stock, 1 Low Stock ──
  {
    id: "grain-01",
    name: "Basmati Rice 5kg",
    category: "Grains & Rice",
    price: 8.99,
    unit: "per bag",
    stockStatus: "In Stock",
    description: "Premium long-grain basmati rice, perfect for jollof and fried rice dishes.",
    placeholderColor: COLORS.grain,
  },
  {
    id: "grain-02",
    name: "Garri (White) 2kg",
    category: "Grains & Rice",
    price: 4.50,
    unit: "per bag",
    stockStatus: "In Stock",
    description: "Finely ground white garri for eba and garri soaking.",
    placeholderColor: COLORS.grain,
  },
  {
    id: "grain-03",
    name: "Plantain Fufu Flour 1kg",
    category: "Grains & Rice",
    price: 5.99,
    unit: "per pack",
    stockStatus: "In Stock",
    description: "Instant plantain fufu flour — just add hot water and stir.",
    placeholderColor: COLORS.grain,
  },
  {
    id: "grain-04",
    name: "Semolina 1kg",
    category: "Grains & Rice",
    price: 3.49,
    unit: "per pack",
    stockStatus: "In Stock",
    description: "Golden semolina flour for smooth, stretchy swallow.",
    placeholderColor: COLORS.grain,
  },
  {
    id: "grain-05",
    name: "Pounded Yam Flour 2kg",
    category: "Grains & Rice",
    price: 7.99,
    unit: "per bag",
    stockStatus: "Low Stock",
    description: "Authentic pounded yam flour, silky texture for soups and stews.",
    placeholderColor: COLORS.grain,
  },
  {
    id: "grain-06",
    name: "Brown Rice 2kg",
    category: "Grains & Rice",
    price: 5.49,
    unit: "per bag",
    stockStatus: "In Stock",
    description: "Whole grain brown rice, nutty flavor and extra fiber.",
    placeholderColor: COLORS.grain,
  },

  // ── Cooking Oils (5): 3 In Stock, 1 Low Stock, 1 Out of Stock ──
  {
    id: "oil-01",
    name: "Palm Oil 1L",
    category: "Cooking Oils",
    price: 6.99,
    unit: "per bottle",
    stockStatus: "In Stock",
    description: "Pure red palm oil for authentic West African soups and stews.",
    placeholderColor: COLORS.oil,
  },
  {
    id: "oil-02",
    name: "Coconut Oil 500ml",
    category: "Cooking Oils",
    price: 5.49,
    unit: "per bottle",
    stockStatus: "In Stock",
    description: "Cold-pressed virgin coconut oil for cooking and skincare.",
    placeholderColor: COLORS.oil,
  },
  {
    id: "oil-03",
    name: "Groundnut Oil 1L",
    category: "Cooking Oils",
    price: 7.49,
    unit: "per bottle",
    stockStatus: "Low Stock",
    description: "Rich groundnut oil, ideal for frying and traditional sauces.",
    placeholderColor: COLORS.oil,
  },
  {
    id: "oil-04",
    name: "Shea Butter (Cooking) 500g",
    category: "Cooking Oils",
    price: 9.99,
    unit: "per jar",
    stockStatus: "Out of Stock",
    description: "Unrefined shea butter for Northern Nigerian and Ghanaian recipes.",
    placeholderColor: COLORS.oil,
  },
  {
    id: "oil-05",
    name: "Vegetable Oil 5L",
    category: "Cooking Oils",
    price: 11.99,
    unit: "per bottle",
    stockStatus: "In Stock",
    description: "Economy-size vegetable oil for everyday cooking needs.",
    placeholderColor: COLORS.oil,
  },

  // ── Spices & Seasonings (6): 4 In Stock, 1 Low Stock, 1 Out of Stock ──
  {
    id: "spice-01",
    name: "Cameroon Pepper (Ground) 100g",
    category: "Spices & Seasonings",
    price: 3.99,
    unit: "per pack",
    stockStatus: "In Stock",
    description: "Fiery ground Cameroon pepper for pepper soup and suya.",
    placeholderColor: COLORS.spice,
  },
  {
    id: "spice-02",
    name: "Suya Spice Mix 200g",
    category: "Spices & Seasonings",
    price: 4.49,
    unit: "per pack",
    stockStatus: "In Stock",
    description: "Authentic suya spice blend with groundnut powder and chili.",
    placeholderColor: COLORS.spice,
  },
  {
    id: "spice-03",
    name: "Maggi Cubes (Box of 100)",
    category: "Spices & Seasonings",
    price: 6.99,
    unit: "per box",
    stockStatus: "In Stock",
    description: "Classic seasoning cubes — an essential in every African kitchen.",
    placeholderColor: COLORS.spice,
  },
  {
    id: "spice-04",
    name: "Dried Crayfish 200g",
    category: "Spices & Seasonings",
    price: 8.49,
    unit: "per pack",
    stockStatus: "Low Stock",
    description: "Ground dried crayfish for rich, umami depth in soups.",
    placeholderColor: COLORS.spice,
  },
  {
    id: "spice-05",
    name: "Ogiri (Locust Bean) 100g",
    category: "Spices & Seasonings",
    price: 3.49,
    unit: "per pack",
    stockStatus: "Out of Stock",
    description: "Fermented locust bean paste for traditional Yoruba soups.",
    placeholderColor: COLORS.spice,
  },
  {
    id: "spice-06",
    name: "Curry Powder 250g",
    category: "Spices & Seasonings",
    price: 2.99,
    unit: "per pack",
    stockStatus: "In Stock",
    description: "Caribbean-style curry powder blend for curried goat and chicken.",
    placeholderColor: COLORS.spice,
  },

  // ── Canned & Preserved (6): 5 In Stock, 1 Out of Stock ──
  {
    id: "can-01",
    name: "Sardines in Tomato Sauce",
    category: "Canned & Preserved",
    price: 2.49,
    unit: "per tin",
    stockStatus: "In Stock",
    description: "Tinned sardines in rich tomato sauce, great with bread or rice.",
    placeholderColor: COLORS.canned,
  },
  {
    id: "can-02",
    name: "Corned Beef 340g",
    category: "Canned & Preserved",
    price: 4.99,
    unit: "per tin",
    stockStatus: "In Stock",
    description: "Premium corned beef — fry with onions for a quick protein.",
    placeholderColor: COLORS.canned,
  },
  {
    id: "can-03",
    name: "Tomato Paste 400g",
    category: "Canned & Preserved",
    price: 1.99,
    unit: "per tin",
    stockStatus: "In Stock",
    description: "Concentrated tomato paste for jollof rice and stew bases.",
    placeholderColor: COLORS.canned,
  },
  {
    id: "can-04",
    name: "Palm Cream Concentrate 400ml",
    category: "Canned & Preserved",
    price: 3.49,
    unit: "per tin",
    stockStatus: "Out of Stock",
    description: "Ready-to-use palm cream for banga and palm nut soups.",
    placeholderColor: COLORS.canned,
  },
  {
    id: "can-05",
    name: "Coconut Milk 400ml",
    category: "Canned & Preserved",
    price: 2.29,
    unit: "per tin",
    stockStatus: "In Stock",
    description: "Creamy coconut milk for Caribbean curries and desserts.",
    placeholderColor: COLORS.canned,
  },
  {
    id: "can-06",
    name: "Butter Beans 400g",
    category: "Canned & Preserved",
    price: 1.79,
    unit: "per tin",
    stockStatus: "In Stock",
    description: "Tender butter beans, ready for stews and salads.",
    placeholderColor: COLORS.canned,
  },

  // ── Beverages (5): 4 In Stock, 1 Low Stock ──
  {
    id: "bev-01",
    name: "Malt Drink (Pack of 6)",
    category: "Beverages",
    price: 7.99,
    unit: "per pack",
    stockStatus: "In Stock",
    description: "Classic malt drink pack — sweet, smooth, non-alcoholic.",
    placeholderColor: COLORS.beverage,
  },
  {
    id: "bev-02",
    name: "Supermalt 330ml",
    category: "Beverages",
    price: 1.49,
    unit: "per bottle",
    stockStatus: "In Stock",
    description: "The original Supermalt — a diaspora favorite since day one.",
    placeholderColor: COLORS.beverage,
  },
  {
    id: "bev-03",
    name: "Ginger Beer 330ml",
    category: "Beverages",
    price: 1.79,
    unit: "per bottle",
    stockStatus: "In Stock",
    description: "Spicy Caribbean ginger beer with a real kick.",
    placeholderColor: COLORS.beverage,
  },
  {
    id: "bev-04",
    name: "Bissap (Hibiscus) Tea 20 Bags",
    category: "Beverages",
    price: 3.99,
    unit: "per box",
    stockStatus: "Low Stock",
    description: "Natural hibiscus tea bags — serve hot or as cold zobo.",
    placeholderColor: COLORS.beverage,
  },
  {
    id: "bev-05",
    name: "Ovaltine 400g",
    category: "Beverages",
    price: 6.49,
    unit: "per jar",
    stockStatus: "In Stock",
    description: "Chocolatey malt drink mix — a breakfast staple across West Africa.",
    placeholderColor: COLORS.beverage,
  },

  // ── Household (4): 4 In Stock ──
  {
    id: "house-01",
    name: "African Black Soap 200g",
    category: "Household",
    price: 4.99,
    unit: "per bar",
    stockStatus: "In Stock",
    description: "Traditional raw black soap for face and body care.",
    placeholderColor: COLORS.household,
  },
  {
    id: "house-02",
    name: "Shea Butter (Body) 500g",
    category: "Household",
    price: 8.99,
    unit: "per jar",
    stockStatus: "In Stock",
    description: "Pure unrefined shea butter for deep skin moisturizing.",
    placeholderColor: COLORS.household,
  },
  {
    id: "house-03",
    name: "Incense Sticks (Assorted) 50pk",
    category: "Household",
    price: 3.49,
    unit: "per pack",
    stockStatus: "In Stock",
    description: "Mixed fragrance incense sticks for home and spiritual use.",
    placeholderColor: COLORS.household,
  },
  {
    id: "house-04",
    name: "Chewing Sponge (Pack of 5)",
    category: "Household",
    price: 2.99,
    unit: "per pack",
    stockStatus: "In Stock",
    description: "Natural chewing sponge sticks for traditional dental care.",
    placeholderColor: COLORS.household,
  },
];

// ── Seed Orders (12): 3 Pending, 4 Confirmed, 3 Packed, 2 Delivered ──

export const seedOrders: Order[] = [
  {
    id: "order-01",
    reference: "MKT-2026-0001",
    customerName: "Amina Diallo",
    phone: "+44 7700 900101",
    deliveryPreference: "Delivery",
    address: "14 Brixton Market Row, London SW9 8PR",
    items: [
      { productId: "grain-01", productName: "Basmati Rice 5kg", price: 8.99, unit: "per bag", quantity: 2 },
      { productId: "oil-01", productName: "Palm Oil 1L", price: 6.99, unit: "per bottle", quantity: 1 },
      { productId: "spice-03", productName: "Maggi Cubes (Box of 100)", price: 6.99, unit: "per box", quantity: 1 },
    ],
    specialInstructions: "Please double-bag the rice.",
    status: "Delivered",
    total: 31.96,
    createdAt: "2026-03-11T09:15:00Z",
  },
  {
    id: "order-02",
    reference: "MKT-2026-0002",
    customerName: "Kwame Mensah",
    phone: "+44 7700 900102",
    deliveryPreference: "Pickup",
    items: [
      { productId: "bev-01", productName: "Malt Drink (Pack of 6)", price: 7.99, unit: "per pack", quantity: 3 },
      { productId: "can-02", productName: "Corned Beef 340g", price: 4.99, unit: "per tin", quantity: 2 },
    ],
    status: "Delivered",
    total: 33.95,
    createdAt: "2026-03-12T11:30:00Z",
  },
  {
    id: "order-03",
    reference: "MKT-2026-0003",
    customerName: "Chioma Obi",
    phone: "+44 7700 900103",
    deliveryPreference: "Delivery",
    address: "27 Peckham High Street, London SE15 5EB",
    items: [
      { productId: "grain-05", productName: "Pounded Yam Flour 2kg", price: 7.99, unit: "per bag", quantity: 1 },
      { productId: "spice-04", productName: "Dried Crayfish 200g", price: 8.49, unit: "per pack", quantity: 2 },
      { productId: "can-03", productName: "Tomato Paste 400g", price: 1.99, unit: "per tin", quantity: 4 },
    ],
    status: "Packed",
    total: 32.93,
    createdAt: "2026-03-14T14:00:00Z",
  },
  {
    id: "order-04",
    reference: "MKT-2026-0004",
    customerName: "Fatou Sow",
    phone: "+44 7700 900104",
    deliveryPreference: "Pickup",
    items: [
      { productId: "oil-03", productName: "Groundnut Oil 1L", price: 7.49, unit: "per bottle", quantity: 2 },
      { productId: "spice-01", productName: "Cameroon Pepper (Ground) 100g", price: 3.99, unit: "per pack", quantity: 1 },
    ],
    status: "Packed",
    total: 18.97,
    createdAt: "2026-03-15T10:45:00Z",
  },
  {
    id: "order-05",
    reference: "MKT-2026-0005",
    customerName: "Emeka Nwosu",
    phone: "+44 7700 900105",
    deliveryPreference: "Delivery",
    address: "8 Dalston Lane, London E8 3DF",
    items: [
      { productId: "grain-03", productName: "Plantain Fufu Flour 1kg", price: 5.99, unit: "per pack", quantity: 2 },
      { productId: "spice-02", productName: "Suya Spice Mix 200g", price: 4.49, unit: "per pack", quantity: 3 },
      { productId: "bev-05", productName: "Ovaltine 400g", price: 6.49, unit: "per jar", quantity: 1 },
    ],
    specialInstructions: "Ring the bell twice — intercom is broken.",
    status: "Confirmed",
    total: 31.94,
    createdAt: "2026-03-17T08:20:00Z",
  },
  {
    id: "order-06",
    reference: "MKT-2026-0006",
    customerName: "Ade Ogunleye",
    phone: "+44 7700 900106",
    deliveryPreference: "Pickup",
    items: [
      { productId: "house-01", productName: "African Black Soap 200g", price: 4.99, unit: "per bar", quantity: 3 },
      { productId: "house-02", productName: "Shea Butter (Body) 500g", price: 8.99, unit: "per jar", quantity: 1 },
    ],
    status: "Confirmed",
    total: 23.96,
    createdAt: "2026-03-18T13:10:00Z",
  },
  {
    id: "order-07",
    reference: "MKT-2026-0007",
    customerName: "Marie-Claire Toure",
    phone: "+44 7700 900107",
    deliveryPreference: "Delivery",
    address: "51 Lewisham Way, London SE14 6QD",
    items: [
      { productId: "can-01", productName: "Sardines in Tomato Sauce", price: 2.49, unit: "per tin", quantity: 6 },
      { productId: "can-05", productName: "Coconut Milk 400ml", price: 2.29, unit: "per tin", quantity: 4 },
      { productId: "spice-06", productName: "Curry Powder 250g", price: 2.99, unit: "per pack", quantity: 2 },
    ],
    status: "Packed",
    total: 30.08,
    createdAt: "2026-03-19T16:30:00Z",
  },
  {
    id: "order-08",
    reference: "MKT-2026-0008",
    customerName: "Yusuf Ibrahim",
    phone: "+44 7700 900108",
    deliveryPreference: "Pickup",
    items: [
      { productId: "grain-02", productName: "Garri (White) 2kg", price: 4.50, unit: "per bag", quantity: 3 },
      { productId: "grain-04", productName: "Semolina 1kg", price: 3.49, unit: "per pack", quantity: 2 },
    ],
    status: "Confirmed",
    total: 20.48,
    createdAt: "2026-03-20T09:00:00Z",
  },
  {
    id: "order-09",
    reference: "MKT-2026-0009",
    customerName: "Ngozi Eze",
    phone: "+44 7700 900109",
    deliveryPreference: "Delivery",
    address: "3 Tottenham High Road, London N15 4RX",
    items: [
      { productId: "oil-05", productName: "Vegetable Oil 5L", price: 11.99, unit: "per bottle", quantity: 1 },
      { productId: "bev-03", productName: "Ginger Beer 330ml", price: 1.79, unit: "per bottle", quantity: 6 },
    ],
    specialInstructions: "Leave with the neighbour if I'm not in.",
    status: "Confirmed",
    total: 22.73,
    createdAt: "2026-03-21T12:45:00Z",
  },
  {
    id: "order-10",
    reference: "MKT-2026-0010",
    customerName: "Blessing Okafor",
    phone: "+44 7700 900110",
    deliveryPreference: "Pickup",
    items: [
      { productId: "bev-02", productName: "Supermalt 330ml", price: 1.49, unit: "per bottle", quantity: 12 },
    ],
    status: "Pending",
    total: 17.88,
    createdAt: "2026-03-24T08:30:00Z",
  },
  {
    id: "order-11",
    reference: "MKT-2026-0011",
    customerName: "Sekou Barry",
    phone: "+44 7700 900111",
    deliveryPreference: "Delivery",
    address: "19 Seven Sisters Road, London N7 6AE",
    items: [
      { productId: "grain-01", productName: "Basmati Rice 5kg", price: 8.99, unit: "per bag", quantity: 1 },
      { productId: "oil-01", productName: "Palm Oil 1L", price: 6.99, unit: "per bottle", quantity: 2 },
      { productId: "can-03", productName: "Tomato Paste 400g", price: 1.99, unit: "per tin", quantity: 3 },
      { productId: "spice-03", productName: "Maggi Cubes (Box of 100)", price: 6.99, unit: "per box", quantity: 1 },
    ],
    specialInstructions: "Call before delivery please.",
    status: "Pending",
    total: 34.91,
    createdAt: "2026-03-24T15:20:00Z",
  },
  {
    id: "order-12",
    reference: "MKT-2026-0012",
    customerName: "Abena Asante",
    phone: "+44 7700 900112",
    deliveryPreference: "Pickup",
    items: [
      { productId: "house-03", productName: "Incense Sticks (Assorted) 50pk", price: 3.49, unit: "per pack", quantity: 2 },
      { productId: "bev-04", productName: "Bissap (Hibiscus) Tea 20 Bags", price: 3.99, unit: "per box", quantity: 1 },
      { productId: "oil-02", productName: "Coconut Oil 500ml", price: 5.49, unit: "per bottle", quantity: 1 },
    ],
    status: "Pending",
    total: 16.46,
    createdAt: "2026-03-25T07:45:00Z",
  },
];
